import Nurse1 from "./images/nurse1.jpg";
import Nurse2 from "./images/nurse2.jpg";
import Nurse3 from "./images/nurse3.jpg";

 interface User {
  id: number;
  name: string;
  image: string;
  type: "service" | "banner";
  rating?: number;
  worksCompleted?: number;
  location?: string;
  kmAway?: number;
}

 export const users: User[] = [
  {
    id: 1,
    name: "Sandra Thomas",
    image: Nurse1.src,
    type: "service",  
    rating: 4.5,
    worksCompleted: 14,
    location: "Fort Kochi",
    kmAway: 12,
  },
  {
    id: 2,
    name: "Kripa",
    image: Nurse2.src,
    type: "service",
    rating: 4.7,
    worksCompleted: 18,
    location: "Edappally",
    kmAway: 11,
  },
  {
    id: 3,
    name: "Liya Fathima",
    image: Nurse3.src,
    type: "service",
    rating: 4.6,
    worksCompleted: 16,
    location: "Kaloor",
    kmAway: 10,
  },
  {
    id: 4,
    name: "Theresa Webb",
    image: Nurse1.src,
    type: "service",
    rating: 4.4,
    worksCompleted: 13,
    location: "Vyttila",
    kmAway: 7,
  },
  {
    id: 5,
    name: "Kathryn Murphy",
    image: Nurse2.src,
    type: "service",
    rating: 4.9,
    worksCompleted: 22,
    location: "Panampilly",
    kmAway: 9,
  },
  {
    id: 6,
    name: "Floyd Miles",
    image: Nurse3.src,
    type: "service",
    rating: 4.8,
    worksCompleted: 17,
    location: "Kakkanad",
    kmAway: 15,
  },
  {
    id: 7,
    name: "Ava Johnson",
    image: Nurse1.src,
    type: "service",
    rating: 4.3,
    worksCompleted: 12,
    location: "Palarivattom",
    kmAway: 8,
  },
  {
    id: 8,
    name: "Noah Bennett",
    image: Nurse2.src,
    type: "service",
    rating: 4.6,
    worksCompleted: 19,
    location: "Aluva",
    kmAway: 18,
  },
  {
    id: 9,
    name: "Maya Patel",
    image: Nurse3.src,
    type: "service",
    rating: 4.2,
    worksCompleted: 11,
    location: "Tripunithura",
    kmAway: 13,
  },
  {
    id: 10,
    name: "Ethan Clark",
    image: Nurse3.src,
    type: "service",
    rating: 4.7,
    worksCompleted: 15,
    location: "Ernakulam",
    kmAway: 6,
  },
  {
    id: 11,
    name: "Banner",
    image: Nurse1.src,
    type: "banner", 
    rating: 4.4,
    worksCompleted: 14,
    location: "Kaloor",
    kmAway: 9,
  },
  {
    id: 12,
    name: "Olivia Chen",
    image: Nurse1.src,
    type: "service",
    rating: 4.4,
    worksCompleted: 14,
    location: "Kaloor",
    kmAway: 9,
  },
  {
    id: 13,
    name: "Lucas Martin",
    image: Nurse2.src,
    type: "service",
    rating: 4.8,
    worksCompleted: 20,
    location: "Edappally",
    kmAway: 10,
  },
  {
    id: 14,
    name: "Isabella Khan",
    image: Nurse3.src,
    type: "service",
    rating: 4.5,
    worksCompleted: 18,
    location: "Fort Kochi",
    kmAway: 14,
  },
  {
    id: 15,
    name: "Arjun Verma",
    image: Nurse1.src,
    type: "service",
    rating: 4.6,
    worksCompleted: 21,
    location: "Vyttila",
    kmAway: 11,
  },
  {
    id: 16,
    name: "Emily Davis",
    image: Nurse2.src,
    type: "service",
    rating: 4.7,
    worksCompleted: 19,
    location: "Panampilly",
    kmAway: 10,
  },
];